### ISSUE TITLE
Add ability to pass parameters

### ISSUE THREAD

**Issue by 18510047382** [pegjs/pegjs#617] opened 2019-06-03 09:01 UTC
Can you add the ability that I can pass parameters to the rule?
Because I really need it! :)

**Comment by Mingun** [comment] 2019-06-03 13:17
What kind of parameters you mean? You can use `options` in the action and predicate code as well as in initializer. If you mean template rules, that already tracked in #45

**Comment by 18510047382** [comment] 2019-06-03 23:55
Yes, I mean "template rules", and I hope you can add this feature!

**Comment by futagoza** [comment] 2019-06-04 19:13
Closing, as Mingun mention, duplicate of #45

**Closed by futagoza** 2019-06-04 19:13 UTC
