### ISSUE TITLE
Rules can't contain quoted braces unless they are balanced

### ISSUE THREAD

**Issue by cscott** [pegjs/pegjs#352] opened 2015-07-09 15:07 UTC
The grammar for peg.js rules says:
```
SourceCharacter
  = .

CodeBlock "code block"
  = "{" code:Code "}" { return code; }

Code
  = $((![{}] SourceCharacter)+ / "{" Code "}")*
```

This means that the following causes a syntax error:
```
myrule = "{" { return "{"; }
```
because the quoted brace is unbalanced.

A fix would be something like:
```
Code
  = $(Comment / StringLiteral / (![{}"'] SourceCharacter)+ / "{" Code "}")*
```
Which would allow braces and quotes (even unbalanced ones!) in comments or string literals.

**Comment by cscott** [comment] 2015-07-09 17:09
Oh, I forgot that you need to match RegExp in there, too.  But you certainly don't need a complete JavaScript grammar (as #4, #29, #89 seem to claim).  The "just match literals" approach is how parser generators have "always" done this, back to bison/yacc/JavaCUP/etc.

Anyway, the proper fix including even RegExps (which are a corner case!) is something like:
```
Code
  = $(Comment / RegExp / StringLiteral / (![{}"'] SourceCharacter)+ / "{" Code "}")*

RegExp 
  = $( "/" !"*" RegExpBody+ "/" )
RegExpBody
  = RegExpClass / RegExpEscape / !LineTerminator [^\[\/\\]
RegExpEscape
  = "\\" !LineTerminator SourceCharacter
RegExpClass
  = "[" (RegExpEscape / !LineTerminator [^\]\\] )* "]"
```

**Comment by dmajda** [comment] 2015-07-10 12:23
This is a duplicate of #89.

**Closed by dmajda** 2015-07-10 12:23 UTC
