### ISSUE TITLE
PEG.buildParser efficiency

### ISSUE THREAD

**Issue by rymohr** [pegjs/pegjs#61] opened 2011-12-06 00:01 UTC
What's the proper way to efficiently define a grammar that includes hundreds (if not thousands) of possible values for a given rule?

I'm using PEG.js to drive an autocomplete on my site and it was working great until the number of values grew into the couple hundred.  The parser is built on the fly from a dynamically generated grammar, and it typically locks up the browser for a good 20-30 seconds while building the parser.

Here's an example gist you can try out to see the delay I'm talking about.

https://gist.github.com/1435954

**Comment by dmajda** [comment] 2015-08-14 13:04
The original Gist is gone (so this is not reproducible anymore), the code generator was rewritten meanwhile, and there are no users complaining about this bug since 2012. Closing.

**Closed by dmajda** 2015-08-14 13:04 UTC
Labels: Performance
