### ISSUE TITLE
Example javascript grammar does not parse functions returning a value as an assignment

### ISSUE THREAD

**Issue by cakesmith** [pegjs/pegjs#286] opened 2014-08-29 20:56 UTC
Using the example javascript grammar with the input:
```js
var A = (function() {
   var B = false;
   return B;
}())
```
results in the code:
```
{
   "type": "Program",
   "body": [
      {
         "type": "VariableDeclaration",
         "declarations": [
            {
               "type": "VariableDeclarator",
               "id": {
                  "type": "Identifier",
                  "name": "A"
               },
               "init": []
            }
         ]
      }
   ]
}
```
Is there any way to expand the `init` section to at least include the variable `B`'s declaration? I'm working on a project that scans javascript code to identify the declared variables and I need to be able to determine which variables are being declared from within a function closure as opposed to which ones aren't.

**Comment by ab34** [comment] 2015-02-13 10:46
Yes, the web version does not produce a valid json for the ast.

Please look at the answer to this issue:
https://github.com/pegjs/pegjs/issues/309

**Comment by dmajda** [comment] 2015-04-08 07:14
Thanks for the report, this is duplicate of https://github.com/pegjs/website/issues/5. Closing.

**Closed by dmajda** 2015-04-08 07:14 UTC
