### ISSUE TITLE
Runtime errors in actions have zero context in parser error messages

### ISSUE THREAD

**Issue by alexchandel** [pegjs/pegjs#559] opened 2018-01-22 03:43 UTC
### Issue type

* [x] Bug Report

### Description

A `TypeError` in an action yields no location or contextualinformation on the source of the error.

### Steps to Reproduce

1. Paste the grammar below into the [online version](https://pegjs.org/online)
2. Paste `1,2,3` in the input

**Example code:**

```pegjs
expr = e:int { return e.join('') }
list = h:int t:(',' int)* { return [h].concat(t.map(function (e) {return e[1]})) }
int = i:[0-9]+ { i.join('') }
```

**Expected behavior:**

Notice the accidental error in the `int` rule, causing it to return `undefined`. `expr` calls `join` on `undefined`, triggering a TypeError with the message `Cannot read property 'join' of undefined`. Location information should be given in the error message.

**Actual behavior:** No location or context is given. The source of the error is a mystery.

### System

**PEG.js:** **Node.js:** **NPM:** **Editor:** https://pegjs.org/online
**Browser:** Chrome
**OS:** macOS

**Comment by polkovnikov-ph** [comment] 2018-01-22 07:20
That's an issue on website. It should probably go [here](https://github.com/pegjs/website/issues). Stacktrace in given example is
```
VM484:1 TypeError: Cannot read property 'join' of undefined
    at peg$c0 (eval at build (online.js:61), <anonymous>:144:41)
    at peg$parseexpr (eval at build (online.js:61), <anonymous>:295:14)
    at Object.peg$parse [as parse] (eval at build (online.js:61), <anonymous>:405:18)
    at parse (online.js:98)
    at buildAndParse (online.js:123)
    at online.js:143
```
which is kinda readable. `peg$parseexpr` tells that happened inside of `expr`, and `c0` is just an internal name for an action.

Currently website doesn't print stacktrace, but you can put breakpoint on `online.js:113`.

**Comment by Mingun** [comment] 2018-01-22 11:56
This is duplicate of #93

**Comment by futagoza** [comment] 2018-01-22 13:40
Closing, answered by @polkovnikov-ph  and like @Mingun mentioned, this issue is the same as #93

**Closed** 2018-01-22 13:39 UTC

**Comment by polkovnikov-ph** [comment] 2018-01-22 14:01
@futagoza I've made a PR for the new version of website to David, and he rejected it, because it changed too much of the code. Even though I don't find my old PR a good piece of code now, and would totally rewrite it, I still find website in a big need of change.

Would you mind if I took responsibility for the website on me?

**Comment by futagoza** [comment] 2018-01-22 14:25
@polkovnikov-ph wrong issue to be asking me about this 🙅‍♂️ Open a new issue on the pegjs-website repo, tell me what your thinking of doing, and we will see from there 😄

**Comment by polkovnikov-ph** [comment] 2018-01-22 15:03
@futagoza I've had a thought it's the wrong place to ask, but for whatever reason decided that it's still worth a try. :)
