### ISSUE TITLE
The most incomprehensible readme I've ever come across

### ISSUE THREAD

**Issue by cyllu2** [pegjs/pegjs#478] opened 2016-12-03 04:41 UTC
Most readmes and docs are very bad, but this one takes the cake.

An example of its terribleness:

> To generate a parser from your grammar, use the pegjs command:
> 
> `$ pegjs -o arithmetics-parser.js arithmetics.pegjs`

Where am I supposed to do this? You just told me to install it via `npm install` so how should my command prompt have access to something called `pegjs`? And what the heck is `arithmetcs.pegjs`? Is that what it has to be called? And do I have to do this to use it or can I skip this step?

Another example is this bit of example code:

```
parser.parse("abba"); // returns ["a", "b", "b", "a"]

parser.parse("abcd"); // throws an exception
```

What the fuck? Why would "abba" return something nice and "abcd" throw an exception?!!?!?!?! What's the difference of these two strings? I'm guessing this depends on the grammar, but having these right next to each other with no explanation given is beyond retarded.

Then you dive straight in:

> Let's look at example grammar that recognizes simple arithmetic expressions like 2*(3+4). A parser generated from this grammar computes their values.
> 
> `Impossible to read code.`

No warm-up, just straight to ass-fuckery.

Thanks a lot.

Another example of something you NEVER explain:

```
additive
  = left:multiplicative "+" right:additive { return left + right; }
  / multiplicative
```

What's `/ multiplicative` after the code piece? It's not a comment. It's... something. But you never explain it, so it's impossible to know.

Also, there is literally no walkthrough on any special characters or anything. Am I supposed to just GUESS? I want to match ANY character but an hour of googling turned up absolutely nothing. Asterisk doesn't work. Dot notation doesn't work. MAYBE IF YOU COULD INCLUDE ACTUAL DOCUMENTATION THAT WOULD HELP.

**Comment by dmajda** [comment] 2016-12-03 09:57
@cyllu2 I hope you feel relieved now. Be aware that if you continue in this style, you’ll end up blocked from this repository. I expect the communication here to be civil, constructive, and in good faith.

Closing as a duplicate of #42.

**Closed by dmajda** 2016-12-03 09:57 UTC

**Comment by cyllu2** [comment] 2016-12-03 18:29
Why would I feel relieved?
