### ISSUE TITLE
travis: no such file or directory

### ISSUE THREAD

**Issue by futagoza** [pegjs/pegjs#434] opened 2016-07-04 02:51 UTC
SEE: [https://travis-ci.org/futagoza/ePEG.js/builds](https://travis-ci.org/futagoza/ePEG.js/builds)

If you look at the first 9 build attempts at [travis](https://travis-ci.org/futagoza/ePEG.js/builds) you will notice it keeps failing because of the ENOENT error 'No such file or directory', but at build 10 this is fixed.

It seems the error was only popping up because of the command line:
```bash
pegjs --output lib/parser.js src/parser.pegjs
```

But it worked as soon as I put my parser generator into a JavaScript file and ran it via:
```bash
node scripts/generate-parser.js
```

**Comment by dmajda** [comment] 2016-07-04 07:40
@futagoza Please provide steps to reproduce the problem using an official PEG.js release or code from master. I won’t debug CI builds of third-party projects. Thanks.

**Comment by futagoza** [comment] 2016-07-04 12:51
@dmajda which do you mean:
1) to use the npm package [pegjs](https://www.npmjs.com/package/pegjs) instead of [pegjs-dev](https://www.npmjs.com/package/pegjs-dev)
2) something other then [https://github.com/futagoza/ePEG.js](https://github.com/futagoza/ePEG.js)

**Comment by futagoza** [comment] 2016-07-04 14:19
I used to use _[https://www.npmjs.com/package/pegjs](https://www.npmjs.com/package/pegjs)_, and never had this issue with Travis when using PEG.js's CLI, but after switching to the latest changes via _[https://www.npmjs.com/package/pegjs-dev](https://www.npmjs.com/package/pegjs-dev)_, I had started using scripts so that I could do some pre-processing work on the grammar.

Now when I started work on _[https://github.com/futagoza/ePEG.js](https://github.com/futagoza/ePEG.js)_ I decided to use PEG.js's CLI since I didn't require the need of any pre-processing, but found this bug via Travis.

From what I can tell, it seems to be only cropping up on Linux (Travis only use's Linux, doesn't it?), where on my OS (Windows 10 Home x64) it works fine, via CLI or module, weather it's `pegjs` or `pegjs-dev`

**Comment by dmajda** [comment] 2016-07-14 07:47
> @dmajda which do you mean:
1) to use the npm package [pegjs](https://www.npmjs.com/package/pegjs) instead of [pegjs-dev](https://www.npmjs.com/package/pegjs-dev)
2) something other then [https://github.com/futagoza/ePEG.js](https://github.com/futagoza/ePEG.js)

Both, really. The issue is that both the `pegjs-dev` package and ePEG.js introduce additional variables into the equation, making it possible that the bug lies there, not in PEG.js itself. This is why I insisted on reproducing the problem with PEG.js itself.

The way I see it, in situations like this the burden of proof that the bug is indeed in PEG.js lies on the reporter. If he/she can’t provide such proof or at least a convincing argument, I have to assume the bug lies elsewhere. Anything else would mean I’d end up debugging third-party code, which is simply something I’m not willing to do.

-----

Anyway, thanks for the reproducing steps. I distilled them into a shell script which I [put up as a gist](https://gist.github.com/dmajda/b4269dae6829ec12835a32737e8b2bfb). I tried to run this script in two environments:

  * OS X El Capitan (10.11.5) with Node.js 6.0.0 installed via `nvm`.
  * Ubuntu 14.04 with Node.js 6.0.0 installed via `nvm`.

In both cases there was no error and the parser was generated in `lib/parser.js`. This indicates `bin/pegjs` works just fine.

To proceed further I need to reproduce the problem. If you can reproduce it in some environment with the script I wrote (or some modification of it), please describe such environment. Otherwise I’ll have to close this bug.

**Comment by futagoza** [comment] 2016-07-16 01:45
I just tried it (the '434.sh' script you provided) on both my Windows 10 laptop (using Cygwin) and on Linux (using Travis), and it seems to work fine.

**Closed** 2016-07-16 02:09 UTC
