### ISSUE TITLE
Reproducable browser freezer

### ISSUE THREAD

**Issue by meglio** [pegjs/pegjs#288] opened 2014-08-30 06:55 UTC
Try this in online editor, Google Chrome will freeze all the time:

    start
      = expr
    expr = (expr1) *
    expr1 = "a" / "b" / formatting
    formatting = (" " / "\n" / "\t") * { return undefined; }

**Comment by sarus** [comment] 2015-03-13 00:40
It would be great to have some sort of solution to this.  I constantly freeze the browser when I'm editing a grammar using the online editor.  Maybe some sort of loop detection logic based on a timeout?  Or maybe even just a switch where you can toggle off the automatic compilation of the grammar (although this would get rid of the really nice ability to just type in changes to your grammar and see the result).  

You could get around this by adding a shortcut key to compile the grammar if the automatic compilation is turned off.  That way it would still be nice and fast to edit and when you're ready compile and view the results.

Thanks!

**Comment by dmajda** [comment] 2015-03-20 12:14
This is a duplicate of #26.

**Closed by dmajda** 2015-03-20 12:14 UTC
