### ISSUE TITLE
Failure to match the expression because of the "callee" string in the action block

### ISSUE THREAD

**Issue by skarkalas** [pegjs/pegjs#350] opened 2015-07-04 08:16 UTC
power
  = whitespace left:primary whitespace operator:power_operator whitespace right:power whitespace
  {
	return {
		"type":"CallExpression",
		"callee": {
			"type":"MemberExpression",
			"computed":false,
			"object":{"type":"Identifier","name":"Math"},
			"property":{"type":"Identifier","name":"pow"}
		},
		"arguments":[left,right]
	};
  }
  / primary

The string "callee" causes the whole thing to fail. 
![callee1](https://cloud.githubusercontent.com/assets/2505429/8507135/c32b2f2a-222c-11e5-9353-108af86f6222.png)
![callee2](https://cloud.githubusercontent.com/assets/2505429/8507136/c6901f22-222c-11e5-8868-86c4c1cac5a4.png)

**Comment by dmajda** [comment] 2015-07-06 16:43
Thanks for the report, it looks like a duplicate of https://github.com/pegjs/website/issues/5.

**Closed by dmajda** 2015-07-06 16:43 UTC

**Comment by fnogatz** [comment] 2015-07-16 07:56
The same applies for parsing the term `f(3)`:
![screenshot from 2015-07-16 09 54 19](https://cloud.githubusercontent.com/assets/881988/8718018/db81b1b6-2ba0-11e5-8793-ed8d1b33a8c1.png)
