### ISSUE TITLE
ES2015-style parameterized rules

### ISSUE THREAD

**Issue by Jamesernator** [pegjs/pegjs#466] opened 2016-11-01 22:24 UTC
When looking through the specification for ECMAScript I found an interesting notion of parameters to rules which allows generating rulesets easily where there's a lot of overlap (its use in ECMAScript is primarily for parsing yield/return statements differently to regular ones as yield/return are only valid in certain contexts) e.g.:

```
Statement[Return] ::
    IfStatement[?Return]
    ContinueStatement
    [+Return] ReturnStatement
    ...
```
becomes two rules

```
Statement ::
    IfStatement
    ContinueStatement
    ...

Statement_Return ::
    IfStatement_Return
    ContinueStatement
    ReturnStatement
```

As per the examples its really good at describing contexts that are virtually identical but allow additional statements e.g. the main use in ECMAScript is for yield/return.

I could see something like working in PEG.js quite easily for example:

```
// We can't use square brackets because of char sequences so I just used ::<variables> for exposition
// obviously there's probably a better syntax
Statement::(Return)
    = IfStatement::(?Return)
    / ContinueStatement
    / ::(+Return) ReturnStatement
```

This would be equivalent to the following PEG.js grammar:

```
Statement
    = IfStatement
    / ContinueStatement

Statement_Return // Plain text substitution almost certainly is a bad idea but this is expositive
    = IfStatement_Return
    / ContinueStatement
    / ReturnStatement

```

Obviously the above example is just exposition, but I'm pretty sure something of the form could work.

**Comment by valtih1978** [comment] 2016-11-03 13:42
Exactly! Normal peg parsers (PEG.js) allow parametrized rules to the full extent. [Look at FastParse](http://www.lihaoyi.com/post/EasyParsingwithParserCombinators.html#recursive-parsers) (parser combinators provide the same):

It allows you to call `" ".rep(1)`, which means that we have exactly one ws. It also allows to build parenthized expressions like

```
sep(child, separator = ",") = sep1(child) | empty_list
sep1(child, separator = ",") = child (sep child)*
par(child) = "(" child ")"
func_declaration = name par(sep(name ":" type)) body
func_call = name par(sep(expr))
```
That is [a simpler way to implement a list with separator](https://github.com/pegjs/pegjs/issues/107).

**Comment by valtih1978** [comment] 2016-11-03 15:47
I have found that this is a duplicate of #45.

**Comment by Jamesernator** [comment] 2016-11-04 01:09
I don't believe I'm asking for the same thing as #45 although both are intentions to remove duplication of certain things. #45 I think addresses removing duplication in terminal productions 

e.g. Instead of

```
Function
    = "function" ![a-zA-Z]+ ...

YieldExpression
    = "yield" ![a-zA-Z]+

```

```
Keyword(word)
    = word ![a-zA-Z]+ // Matches keywords that isn't a prefix of another word

Function
    = Keyword("function") ...

YieldExpression
    = Keyword("yield") ...
```

which allows for less hassle say if we wanted to change identifiers so they could have numbers and underscores we could just add it into our Keyword definition

```
Keyword(word)
    = word ![_a-zA-Z0-9]+

Function
    = Keyword("function") ...
```

---

My issue is actually about preventing excessive numbers of Non-Terminals for expressing similar but subtlely different Rules. I'll use the Ecmascript's definition of FunctionExpression for ES7 to demonstrate how ridiculous it becomes:

in order to represent the following:

```
AssignmentExpression[In, Yield, Await]::
    ConditionalExpression[?In, ?Yield, ?Await]
    [+Yield] YieldExpression[?In]
    ArrowFunction[?In, ?Yield, ?Await]
    AsyncArrowFunction[?In, ?Yield, ?Await]
    LeftHandSideExpression[?Yield, ?Await] "=" AssignmentExpression[?In, ?Yield, ?Await]
    LeftHandSideExpression[?Yield, ?Await] AssignmentOperatorAssignmentExpression[?In, ?Yield, ?Await]
```

I need the following PEGjs

```
AssignmentExpression
    = ConditionalExpression
    / ArrowFunction
    / AsyncArrowFunction
    / LeftHandSideExpression "=" AssignmentExpression
    / LeftHandSideExpression AssignmentOperatorAssignmentExpression

AssignmentExpression_In
    = ConditionalExpression_In
    / ArrowFunction_In
    / AsyncArrowFunction_In
    / LeftHandSideExpression "=" AssignmentExpression_In
    / LeftHandSideExpression AssignmentOperatorAssignmentExpression_In

AssignmentExpression_Yield
    = ConditionalExpression_Yield
    / YieldExpression
    / ArrowFunction_Yield
    / AsyncArrowFunction_Yield
    / LeftHandSideExpression_Yield "=" AssignmentExpression_Yield
    / LeftHandSideExpression_Yield AssignmentOperatorAssignmentExpression_Yield

AssignmentExpression_Await
    = ConditionalExpression_Await
    / ArrowFunction_Await
    / AsyncArrowFunction_Await
    / LeftHandSideExpression_Await "=" AssignmentExpression_Await
    / LeftHandSideExpression_Await AssignmentOperatorAssignmentExpression_Await

AssignmentExpression_In_Yield
    = ConditionalExpression_In_Yield
    / YieldExpression_In
    / ArrowFunction_In_Yield
    / AsyncArrowFunction_In_Yield
    / LeftHandSideExpression_Yield "=" AssignmentExpression_In_Yield
    / LeftHandSideExpression_Yield AssignmentOperatorAssignmentExpression_In_Yield

AssignmentExpression_In_Await
    = ConditionalExpression_In_Await
    / ArrowFunction_In_Await
    / AsyncArrowFunction_In_Await
    / LeftHandSideExpression_Await "=" AssignmentExpression_In_Await
    / LeftHandSideExpression_Await AssignmentOperatorAssignmentExpression_In_Await

AssignmentExpression_Yield_Await
    = ConditionalExpression_Yield_Await
    / YieldExpression
    / ArrowFunction_Yield_Await
    / AsyncArrowFunction_Yield_Await
    / LeftHandSideExpression_Yield_Await "=" AssignmentExpression_Yield_Await
    / LeftHandSideExpression_Yield_Await AssignmentOperatorAssignmentExpression_Yield_Await

AssignmentExpression_In_Yield_Await
    = ConditionalExpression_In_Yield_Await
    / YieldExpression_In
    / ArrowFunction_In_Yield_Await
    / AsyncArrowFunction_In_Yield_Await
    / LeftHandSideExpression_Yield_Await "=" AssignmentExpression_In_Yield_Await
    / LeftHandSideExpression_Yield_Await AssignmentOperatorAssignmentExpression_In_Yield_Await
```

Which while doable is still a pain especially when you realise there's still like 50 more: [ECMAScript](https://tc39.github.io/ecma262/#sec-grammar-summary) which is even more with [async functions](https://tc39.github.io/ecmascript-asyncawait/#modified-productions)

**Comment by valtih1978** [comment] 2016-11-06 06:50
I did not get their example but, once you have parametrized rules, you can do whatever, including your examples. Why say that their parametric rules are limited to the keywords? For keywords, we need #470!

**Comment by Jamesernator** [comment] 2016-11-06 21:25
The keyword thing was merely an example demonstrating that #45 allows implementing things in a modular format.

I think I see the thing in #45 that would allow this proposal to be implemented using the `& { <conditional block> }`  which would be an acceptable workaround (if not ideal).

**Comment by jacobp100** [comment] 2016-11-21 12:59
I am also looking for this. My use case would be more like this,

```
AnyOrder2<A, B>
  = a:A _ b:B { return [a, b]; }
  / a:B _ b:A { return [b, a]; }

AnyOrder3<A, B, C>
  = head:A tail:AnyOrder2<B, C> { return [head, ...tail]; }
  / head:B tail:AnyOrder2<A, C> { return [head, ...tail]; }
  / head:C tail:AnyOrder2<A, B> { return [head, ...tail]; }

...

CssFontShorthand
  = keywords:AnyOrder3<CssFontStyle, CssFontVariant, CssFontWeight> _
    size:CssUnit _
    lineHeight:(_ “/“ _ CssUnit _)?
    family:CssFontFamily {
      ...
    }
```

**Comment by Mingun** [comment] 2016-11-21 14:52
@jacobp100, in your case I think, more natural will use the following approach:
```pegjs
CssFont
  = CssFontStyle
  / CssFontVariant
  / CssFontWeight
  ;
CssFontShorthand
 = keywords:(CssFont _)*
   ...
```
The shortcoming the truth is that there is no guarantee of uniqueness of values in the `keywords` array, but this can be checked in action.

**Comment by jacobp100** [comment] 2016-11-21 15:13
That’s not quite what I’m going for. `CssFontStyle` can include `italic`. `CssFontWeight` can include `bold`, and `CssFontVariant` can include `small-caps`. So the following should parse correctly,

```
italic bold small-caps
bold small-caps italic
```

But the following should not parse,

```
bold bold bold
bold italic bold
```

I understand you’d be able to get around using the `AnyOrder3` macro in this one case by writing down all the permutations. But the reality is that in CSS, most shorthands can have multiple orders, and so having a rule that accepts generic parameters would significantly reduce the amount of code.

You can see what I’ve done using Nearley [here](https://github.com/styled-components/css-to-react-native/blob/master/src/grammar.ne): but I have macros for `anyOrder3`, as well as `anyOrderOptional3`, to allow up to any of three defined values to appear in any order. I hope this macro demonstrates my use case at least!

**Comment by dmajda** [comment] 2016-11-30 11:22
While general parametrization (as discussed in #45) is undoubtedly useful, I remain unconvinced of usefulness of implementing ES2015-style parametrization.

Personally, I think the ES2015 grammar is and abomination and it specifies in syntax many things that should be left to semantic analysis. I see the fact that it is hard to express the ES21015 grammar  in PEG.js not as a failure of PEG.js but of the grammar itself. As a result, this example isn’t convincing for me. And I’m not currently aware of any other examples showing a pressing need for this kind of parametrization.

(Note I studied ES2015 only superficially so I welcome any well-informed explanation of why I’m wrong and why the approach chosen by ES2015 creators is actually better than the alternatives.)

---

> You have no right to tell that you have a simple and expressive synthax before you introduce this feature.

@valtih1978 I have a right to say anything that isn’t against the law :-) In any case, PEG.js syntax is more expressive than syntax of many other generators (e.g. various Yacc & Bison clones), which is what this sentence is meant to highlight.

> I am also looking for this. My use case would be more like this,
> 
> ```
> AnyOrder2<A, B>
>   = a:A _ b:B { return [a, b]; }
>   / a:B _ b:A { return [b, a]; }
> 
> AnyOrder3<A, B, C>
>   = head:A _ tail:AnyOrder2<B, C> { return [head, ...tail]; }
>   / head:B _ tail:AnyOrder2<A, C> { return [head, ...tail]; }
>   / head:C _ tail:AnyOrder2<A, B> { return [head, ...tail]; }
> 
> ...
> 
> CssFontShorthand
>   = keywords:AnyOrder3<CssFontStyle, CssFontVariant, CssFontWeight> _
>     size:CssUnit _
>     lineHeight:(_ “/“ _ CssUnit _)?
>     family:CssFontFamily {
>       ...
>     }
> ```

@jacobp100 I think your example supports #45 rather than the kind of parametrization requested here.

**Closed by dmajda** 2016-11-30 11:22 UTC
Labels: Feature

**Comment by valtih1978** [comment] 2016-11-30 12:13
Have everybody appreciated the logic: any parametrized rules are ES2015 parametrized rules, and, therefore, useless anywhere but in ES2015. Who can buy it?

**Comment by dmajda** [comment] 2016-11-30 12:49
> Have everybody appreciated the logic: "any parametrized rules are ES2015 parametrized rules, and, therefore, useless anywhere but in ES2015". Who can buy it?

@valtih1978 Nowhere in my comment did I say anything remotely close to your quote. I never equated the requested ES2015-style parametrization with any other kind nor did I say it is useless outside of ES2015. I just said that based on what I’ve seen so far I don’t think it makes sense to implement it in PEG.js.

You mis-read and then attack — not for the first time. Stop doing that. I expect the discussion here to be civil, constructive, and in good faith.
