### ISSUE TITLE
Weird "{" bug in grammar file javascript section.

### ISSUE THREAD

**Issue by YemSalat** [pegjs/pegjs#388] opened 2015-11-09 05:10 UTC
In the top part of the grammar, where you would define your JavaScript helper functions, etc. - it seems like it is trying to match the number of open and closing "{" / "}" quite 'literally'.

I have a case where I got an extra opening "{" - but it is inside a javascript string literal, so it is not an actual "{"

This is the code:
    {
     var g = "{" // <- ha!
    }

And this is the error: `Line 1, column 1: Expected code block, comment, end of line, identifier or whitespace but "{" found.`

![screen shot 2015-11-09 at 4 06 44 pm](https://cloud.githubusercontent.com/assets/2361381/11026340/59191608-86fc-11e5-9b0f-3cb7db43ca6a.png)

There is also a hack around this, you just need to add a closing "}" somewhere (e.g. inside a comment) `var g = "{"; //  } <- hacked!` But I think this should be fixed.

**Comment by YemSalat** [comment] 2015-11-09 05:35
Sorry, I just noticed this line in the documentation:

>  Curly braces in the initializer code must be balanced.

So this is probably a known behaviour, in that case - please feel free to close this issue.

**Comment by lydell** [comment] 2015-11-22 11:07
Duplicate of #89.

**Closed** 2015-11-27 10:14 UTC
