### ISSUE TITLE
mistaken use of = for : causes generator to hang

### ISSUE THREAD

**Issue by JohnCokerC3** [pegjs/pegjs#294] opened 2014-09-27 17:08 UTC
Probably not a huge deal, but coming from Antlr, I mistakenly used the equal sign instead of a colon and it took me a while to figure out why the generator went into an infinite loop.

    a = b+
    b = ' '* n=c { return n; }
    c = 'c'

**Comment by dmajda** [comment] 2015-04-10 12:53
This is essentially a duplicate of #26 which got recently fixed. Closing.

**Closed by dmajda** 2015-04-10 12:53 UTC
